#!/usr/bin/env python3
import os
from generate_base import (build_page, theory_card, ol_steps, code_block, out_table, viva, kw, tbl, num, cmt, str_, fn)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

def p06():
    aim = """<p class="text-on-surface font-body leading-relaxed text-lg mb-4">
The aim of this practical is to implement absolute data integrity using SQL constraints and to manage database schemas dynamically post-creation utilizing `ALTER` and `DROP` commands. 
The student will aggressively govern the Hospital constraints layer—enforcing Domain, Entity, and Referential locks—and analyze exact violation errors generated by the engine when malicious input is submitted.
</p>"""

    theory = f"""<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
{theory_card("The Role of Constraints in RDBMS","Constraints act as mathematically unbreachable firewalls situated immediately above the hard drive. They ensure data reliability by strictly enforcing conditions before any `INSERT` or `UPDATE` is physically written. If rules are violated, MySQL halts execution and throws an Exception. Entity Integrity ensures no two rows are identical (enforced via `PRIMARY KEY` or `UNIQUE`), while Domain Integrity ensures an isolated column value remains logically sound for that data type (enforced via `NOT NULL`, `CHECK`, and variable type limits).","lg:col-span-2","primary","primary")}
{theory_card("Referential Integrity and Foreign Keys","When normalizing schemas, parent and child tables rely on relationship strings. Referential Integrity ensures that a child table cannot reference a parent id that does not genuinely exist in the parent table. Furthermore, if a DBA attempts to DELETE a parent row (e.g. Department), a strictly configured `FOREIGN KEY` will violently block the deletion (via `RESTRICT`) unless explicitly commanded to `CASCADE` the deletion down through all children, preventing 'orphaned data' from floating indefinitely in the DB.","","secondary","secondary")}
{theory_card("ALTER TABLE: Dynamic Architecture Evolution","In a production matrix, destroying a table to add a new column is financially disastrous because it vaporizes the historical data within. `ALTER TABLE` is used to restructure active tables live. `ADD COLUMN` seamlessly pushes new attributes; `MODIFY COLUMN` shrinks or expands character limits (provided it doesn't truncate existing data); `RENAME COLUMN` updates architectural phrasing, and `DROP COLUMN` forcibly purges an entire column and its payload forever without locking the system.","lg:col-span-2","primary","primary")}
{theory_card("Data Eradication: DELETE vs TRUNCATE vs DROP","`DELETE` is a DML (Data Manipulation) command; it destroys singular rows (leveraging `WHERE`), operates sequentially which is incredibly slow for massive data, and writes to log files meaning you can `ROLLBACK` to recover it. `TRUNCATE` is a DDL command; it physically tears down the internal table payload and rebuilds its hull instaneously, stripping all auto_increment counters down to 1. `DROP` destroys the hull, the framework, the payload, and completely frees up the hard disk memory—it completely vanishes the table entirely.","","secondary","secondary")}
</div>"""

    proc = ol_steps([
        "Authenticate into the MySQL terminal and change environment to `USE hospital_db;`.",
        "Attempt to forcefully insert a corrupted patient record that actively violates the established `CHECK` constraints.",
        "Observe the strict failure trace returned by the MySQL daemon preventing bad integer ingestion.",
        "Utilize `ALTER TABLE` to append a new column accommodating emergency contact data.",
        "Morph the recently appended column utilizing `MODIFY` to expand character capacity limit.",
        "Apply a `UNIQUE` lock on the new column preventing duplicates using `ADD CONSTRAINT`.",
        "Insert a test Department record specifically built to test referential locking structures.",
        "Attempt a `DELETE` against the test Department and observe how existing Foreign Keys react.",
        "Eradicate the `UNIQUE` index constraint applying `DROP INDEX`.",
        "Revert architectural modifications utilizing `DROP COLUMN`.",
        "Initialize a dummy log table, and demonstrate instantaneous clearance applying `TRUNCATE TABLE`.",
        "Conclude architecture manipulation by purging the temporary hull with `DROP TABLE`."
    ])

    code = code_block(f"""{cmt("-- Practical 06: Deep Dive Configuration of Constraints, ALTER, and DROP")}
{kw("USE")} {tbl("hospital_db")};

{cmt("-- 1. CONSTRAINT VIOLATION TESTING")}
{cmt("-- Let's try to pass an illegal negative age, triggering the internal generic CHECK.")}
{cmt("/* ")}
{cmt("   INSERT INTO PATIENT (patient_id, name, age) VALUES ('P999', 'Corrupt Data', -12);")}
{cmt("   EXPECTED MYSQL ENGINE ERROR: Error Code 3819.")}
{cmt("   Check constraint 'patient_chk_1' is violated. Insert is Halted entirely.")}
{cmt("*/")}

{cmt("-- 2. ARCHITECTURAL EXPANSION via ALTER")}
{cmt("-- Adding a completely new attribute while preserving existing patient row data.")}
{kw("ALTER TABLE")} {tbl("DOCTOR")} {kw("ADD COLUMN")} {tbl("emergency_phone")} {kw("VARCHAR")}({num("15")});

{cmt("-- 3. MODIFYING EXISTING ARCHITECTURES")}
{cmt("-- Realizing 15 characters is too short for international codes, we expand it to 20.")}
{kw("ALTER TABLE")} {tbl("DOCTOR")} {kw("MODIFY COLUMN")} {tbl("emergency_phone")} {kw("VARCHAR")}({num("20")});

{cmt("-- 4. ADDING LATE-STAGE CONSTRAINTS")}
{cmt("-- Ensuring no two doctors register the exact identical emergency ping router.")}
{kw("ALTER TABLE")} {tbl("DOCTOR")} {kw("ADD CONSTRAINT")} {tbl("uq_doctor_emg")} {kw("UNIQUE")} ({tbl("emergency_phone")});

{cmt("-- 5. RENAMING SCHEMA STRUCTURES")}
{kw("ALTER TABLE")} {tbl("DOCTOR")} {kw("RENAME COLUMN")} {tbl("emergency_phone")} {kw("TO")} {tbl("contact_router")};

{cmt("-- 6. REFERENTIAL LOCKING ANALYSIS (FOREIGN KEYS)")}
{cmt("-- Attempting to DROP the parent Cardiology Department (dept_id = 1).")}
{cmt("/* ")}
{cmt("   DELETE FROM DEPARTMENT WHERE dept_id = 1;")}
{cmt("   EXPECTED ERROR: Error Code 1451. Cannot delete or update a parent row:")}
{cmt("   a foreign key constraint fails (`hospital_db`.`DOCTOR`, CONSTRAINT ... )")}
{cmt("*/")}

{cmt("-- 7. CONSTRAINT ROLLBCAK / REDUCTION")}
{cmt("-- Standard constraint drops target explicitly named indexes.")}
{kw("ALTER TABLE")} {tbl("DOCTOR")} {kw("DROP INDEX")} {tbl("uq_doctor_emg")};

{cmt("-- 8. ARCHITECTURAL CONTRACTION via DROP COLUMN")}
{kw("ALTER TABLE")} {tbl("DOCTOR")} {kw("DROP COLUMN")} {tbl("contact_router")};

{cmt("-- 9. DESTRUCTION TESTING: TRUNCATE VS DROP")}
{cmt("-- Creating an arbitrary logging cache matrix.")}
{kw("CREATE TABLE")} {tbl("ARBITRARY_LOG")} (
    {tbl("id")} {kw("INT PRIMARY KEY AUTO_INCREMENT")},
    {tbl("ping")} {kw("VARCHAR")}({num("5")})
);
{kw("INSERT INTO")} {tbl("ARBITRARY_LOG")} ({tbl("ping")}) {kw("VALUES")} ({str_("'A'")}),({str_("'B'")}),({str_("'C'")});

{cmt("-- 9A. TRUNCATE leaves the hull structure intact but vaporizes data instantaneously.")}
{kw("TRUNCATE TABLE")} {tbl("ARBITRARY_LOG")};
{cmt("-- 9B. We can prove the structure exists but Auto_Increment reset to 1.")}
{kw("INSERT INTO")} {tbl("ARBITRARY_LOG")} ({tbl("ping")}) {kw("VALUES")} ({str_("'X'")});
{kw("SELECT")} * {kw("FROM")} {tbl("ARBITRARY_LOG")};

{cmt("-- 9C. DROP absolutely obliterates the table physically from disk.")}
{kw("DROP TABLE")} {tbl("ARBITRARY_LOG")};
""")
    output = out_table(
        ["id","ping"],
        [["1","X"]],
        "Result: Table after TRUNCATE and single INSERT (ID reset to 1)"
    )

    conclusion = """<p class="text-on-surface font-body leading-relaxed mb-4">
Through precise interaction with SQL's definition layer, we demonstrated structural agility via ALTER statements, avoiding disastrous table reconstruction processes. We proved conclusively that standard `CHECK` and `FOREIGN KEY` constraints serve as impenetrable application guards against malicious or orphaned payload requests. Finally, by mapping out the lethal differences between TRUNCATE and DROP operations, we highlighted critical operational commands mandatory for system integrity upkeep.
</p>"""
    return build_page(6,"Constraints, ALTER, DROP","Group A","Data Integrity",
        "Managing database schemas post-creation and aggressively enforcing domain integrity guidelines.",
        aim, theory, proc, code, output, conclusion, "")

def p07():
    aim = """<p class="text-on-surface font-body leading-relaxed text-lg mb-4">
The aim of this practical is to master the execution of complex query parameters utilizing advanced structural Data Manipulation Language (DML). 
The student will compose heavily nested queries demonstrating `WHERE` comparisons, aggregate mathematics, strict conditional grouping (`HAVING`), Subqueries distributed across the execution stack, and combinatorial Set logical arrays.
</p>"""

    theory = f"""<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
{theory_card("Filter Operations & Query Architecture","The architecture of a `SELECT` limits exactly which data pipes stream from memory to interface. The `WHERE` clause fundamentally filters payload retrieval on a row-by-row level using operators: Relational (=, !=, &gt;, &lt;=) and Logical (AND, OR, NOT). Pattern strings are located using `LIKE` matrices, lists are scoped utilizing `IN`, ranges leverage `BETWEEN`, and nullity is detected strictly using `IS NULL`. Sequence ordering leverages `ORDER BY` and truncation leverages `LIMIT`.","lg:col-span-2","primary","primary")}
{theory_card("Aggregate Analysis and Conditional Grouping","Raw data frequently lacks analytical clarity until grouped. Aggregate commands (`COUNT`, `SUM`, `AVG`, `MAX`, `MIN`) condense large sets mathematically. Critical rule: `WHERE` clauses cannot perform computation using Aggregates due to SQL execution order targeting `WHERE` *before* aggregation calculation. To filter aggregated grouped arrays, the `HAVING` clause explicitly operates sequentially after `GROUP BY` completes.","","secondary","secondary")}
{theory_card("Subqueries and Nested Extraction","Subqueries are SQL statements embedded implicitly within the clauses of a root SQL statement. A nested subquery is executed only once and its calculated scalar output is injected instantly into the root statement's `WHERE` block. Conversely, a Correlated Subquery creates dramatic algorithmic drag as its embedded query mathematically references variables mapped directly to the root query, forcing the subquery engine to loop and execute individually *for every single row* traversing the outer logic execution matrix.","lg:col-span-2","primary","primary")}
{theory_card("Set Combinatorial Operators","SQL enables directly stitching autonomous query payloads together completely bypassing relational ties via Set Operators. `UNION` glues distinct rows vertically into one super-column stack (purging exact overlap duplicates entirely). `UNION ALL` stacks queries insanely fast while preserving duplicates. While MySQL formally rejects strict `INTERSECT` and `MINUS/EXCEPT` syntaxes, seasoned DBA engineers simulate intersection matrices heavily relying on `IN` bindings nested through subqueries.","","secondary","secondary")}
</div>"""

    proc = ol_steps([
        "Execute basic `WHERE` filtering compounding parameters using `AND`, `OR`, `LIKE`.",
        "Perform exact Nullity parsing explicitly using `IS NOT NULL` and unique parsing via `DISTINCT`.",
        "Utilize numerical boundaries through exact `BETWEEN` calls and array filters via the `IN()` clause.",
        "Render complex Aggregations using `COUNT` and `SUM` paired strategically against `GROUP BY` metrics.",
        "Target the aggregated groupings enforcing boundaries using conditional `HAVING` filters.",
        "Simulate `ROLLUP` functionality to generate massive total aggregation overlays independently.",
        "Write a standard nested Subquery capturing dynamic logic boundaries within the `WHERE` statement.",
        "Write a deeply dynamic Subquery mapping execution to the `FROM` derived structure layout.",
        "Render correlated calculations embedding mathematical relations inside mapping `SELECT` clauses.",
        "Utilize `UNION` logic stringing autonomous tables into generic mapped list blocks vertically.",
        "Simulate a structural `INTERSECT` utilizing boolean overlaps."
    ])

    code = code_block(f"""{cmt("-- Practical 07: Massive Query Expansions (Filtering, Subqueries, Sets, and Grouping)")}
{kw("USE")} {tbl("hospital_db")};

{cmt("-- ────────── BLOCK 1: BOOLEAN FILTERS AND RELATIONAL SEQUENCES ──────────")}
{cmt("-- A: Multi-conditional filtering matching wildcards using 'LIKE'")}
{kw("SELECT")} {tbl("patient_id")}, {tbl("name")}, {tbl("disease")} {kw("FROM")} {tbl("PATIENT")} 
{kw("WHERE")} ({tbl("disease")} = {str_("'Diabetes'")} {kw("OR")} {tbl("disease")} = {str_("'Migraine'")}) 
{kw("AND")} {tbl("name")} {kw("LIKE")} {str_("'%a%'")}
{kw("ORDER BY")} {tbl("name")} {kw("ASC")} {kw("LIMIT")} {num("5")};

{cmt("-- B: Locating exactly nested range arrays leveraging BETWEEN and IN")}
{kw("SELECT")} {tbl("doctor_id")}, {tbl("name")}, {tbl("salary")}, {tbl("dept_id")} {kw("FROM")} {tbl("DOCTOR")} 
{kw("WHERE")} {tbl("salary")} {kw("BETWEEN")} {num("80000")} {kw("AND")} {num("150000")} 
{kw("AND")} {tbl("dept_id")} {kw("IN")} ({num("2")},{num("3")},{num("4")});

{cmt("-- C: Distilling arrays parsing Nullity via IS NOT NULL")}
{kw("SELECT DISTINCT")} {tbl("experience_years")} {kw("FROM")} {tbl("DOCTOR")} 
{kw("WHERE")} {tbl("experience_years")} {kw("IS NOT NULL")} {kw("ORDER BY")} {tbl("experience_years")} {kw("DESC")};

{cmt("-- ────────── BLOCK 2: MATHEMATICAL AGGREGATION AND GROUPING ──────────")}
{cmt("-- A: General aggregate functions computing financial blocks")}
{kw("SELECT")} {fn("COUNT")}(*) {kw("AS")} {tbl("Total_Bills")}, 
       {fn("SUM")}({tbl("total_amount")}) {kw("AS")} {tbl("Total_Cash_Generated")}, 
       {fn("MAX")}({tbl("total_amount")}) {kw("AS")} {tbl("Heaviest_Bill")} 
{kw("FROM")} {tbl("BILL")};

{cmt("-- B: Implementing STRICT GROUPS and post-aggregation HAVING constraints")}
{kw("SELECT")} {tbl("department.dept_id")}, {fn("AVG")}({tbl("salary")}) {kw("AS")} {tbl("Average_Departmental_Pay")} 
{kw("FROM")} {tbl("DOCTOR")} 
{kw("GROUP BY")} {tbl("dept_id")} 
{kw("HAVING")} {tbl("Average_Departmental_Pay")} &gt; {num("100000")}
{kw("ORDER BY")} {tbl("Average_Departmental_Pay")} {kw("DESC")};

{cmt("-- C: Executing mathematical ROLLUP to print generic super-aggregates internally")}
{kw("SELECT")} {tbl("gender")}, {fn("COUNT")}(*) {kw("AS")} {tbl("Patient_Sum")} 
{kw("FROM")} {tbl("PATIENT")} 
{kw("GROUP BY")} {tbl("gender")} {kw("WITH ROLLUP")};

{cmt("-- ────────── BLOCK 3: SUBQUERY MANIPULATION EXTRACTS ──────────")}
{cmt("-- A: Nested WHERE Subquery: Find Doctors making above the global institutional average")}
{kw("SELECT")} {tbl("name")}, {tbl("salary")} {kw("FROM")} {tbl("DOCTOR")} 
{kw("WHERE")} {tbl("salary")} &gt; ({kw("SELECT")} {fn("AVG")}({tbl("salary")}) {kw("FROM")} {tbl("DOCTOR")});

{cmt("-- B: Subquery located securely in FROM clause (Derived Internal Tables)")}
{kw("SELECT")} {tbl("Max_Salary")}, {tbl("Min_Salary")} 
{kw("FROM")} ({kw("SELECT")} {fn("MAX")}({tbl("salary")}) {kw("AS")} {tbl("Max_Salary")}, {fn("MIN")}({tbl("salary")}) {kw("AS")} {tbl("Min_Salary")} {kw("FROM")} {tbl("DOCTOR")}) {kw("AS")} {tbl("derived_pay_matrix")};

{cmt("-- C: Select subquery implementation for calculated output formatting")}
{kw("SELECT")} {tbl("name")}, 
       ({kw("SELECT")} {fn("COUNT")}(*) {kw("FROM")} {tbl("APPOINTMENT")} {kw("WHERE")} {tbl("patient_id")} = {tbl("PATIENT")}.{tbl("patient_id")}) {kw("AS")} {tbl("Appointments_Logged")}
{kw("FROM")} {tbl("PATIENT")} {kw("LIMIT")} {num("4")};

{cmt("-- D: Subquery generating a Correlation matrix (Slow algorithmic execution)")}
{cmt("-- Finding patients whose personal bill is strictly higher than their ward average.")}
{kw("SELECT")} {tbl("patient_id")}, {tbl("total_amount")} {kw("FROM")} {tbl("BILL")} {tbl("b1")}
{kw("WHERE")} {tbl("total_amount")} &gt; (
    {kw("SELECT")} {fn("AVG")}({tbl("total_amount")}) {kw("FROM")} {tbl("BILL")} {tbl("b2")} 
    {kw("WHERE")} {tbl("b1")}.{tbl("paid_status")} = {tbl("b2")}.{tbl("paid_status")}
);

{cmt("-- ────────── BLOCK 4: SET OPERATORS ──────────")}
{cmt("-- A: UNION combinations (Requires perfectly identical column structural definitions)")}
{kw("SELECT")} {tbl("name")} {kw("AS")} {tbl("Global_Entity_Directory")}, {str_("'STAFF'")}, {tbl("doctor_id")} {kw("FROM")} {tbl("DOCTOR")}
{kw("UNION")}
{kw("SELECT")} {tbl("name")}, {str_("'CIVILIAN'")}, {tbl("patient_id")} {kw("FROM")} {tbl("PATIENT")}
{kw("ORDER BY")} {tbl("Global_Entity_Directory")} {kw("ASC LIMIT")} {num("5")};

{cmt("-- B: Simulating INTERSECT (MySQL strictly lacks native INTERSECT structural support)")}
{cmt("-- Identifying patients who have generated BOTH arbitrary appointments AND heavy bills.")}
{kw("SELECT")} {tbl("patient_id")} {kw("FROM")} {tbl("PATIENT")} 
{kw("WHERE")} {tbl("patient_id")} {kw("IN")} ({kw("SELECT")} {tbl("patient_id")} {kw("FROM")} {tbl("APPOINTMENT")})
{kw("AND")} {tbl("patient_id")} {kw("IN")} ({kw("SELECT")} {tbl("patient_id")} {kw("FROM")} {tbl("BILL")});
""")
    output = out_table(
        ["Global_Entity_Directory","'STAFF'","doctor_id"],
        [["Aarav Shah","CIVILIAN","P001"],
         ["Amit Agarwal","STAFF","10"],
         ["Amitabh Sen","CIVILIAN","P011"],
         ["Ananya Iyer","CIVILIAN","P004"],
         ["Anjali Singh","STAFF","6"]],
        "Result: Array mapped horizontally via specific UNION operations."
    )

    conclusion = """<p class="text-on-surface font-body leading-relaxed mb-4">
Through a massive array of Data Manipulation operations, we fully extracted diverse informational layouts utilizing heavily nested conditions. Subqueries operating securely across execution lines proved algorithms can calculate internal constraints dynamically exactly during runtime evaluation. Concomitantly, set operation integrations combined drastically separated architectural blocks to form completely custom super-layers matching targeted extraction schemas definitively without duplicating real database footprints.
</p>"""
    return build_page(7,"SQL Queries","Group B","Data Retrieval",
        "Executing relational, boolean, subquery matrices, set structures, and aggregate query combinations extracting highly tuned datasets.",
        aim, theory, proc, code, output, conclusion, "")

def p08():
    aim = """<p class="text-on-surface font-body leading-relaxed text-lg mb-4">
The aim of this practical is to instantiate dynamic Virtual Tables commonly referred to as `VIEW`s. 
The student will master security layering architectures shielding internal database structures entirely from user exposure while mapping logical simplicity across multi-table query combinations utilizing both updatable checks and fixed view arrays.
</p>"""

    theory = f"""<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
{theory_card("Conceptualizing Semantic Views","Views contain no data independently. A view exists mathematically compiled strictly as a stored pre-validated textual `SELECT` string residing inside the Database meta-catalog. At the precise millisecond a user executes querying logic against a named View, the internal MySQL engine translates the call algorithmically down into executing the complex raw Base Table operations mapped globally underly it. Extremely massive architectures utilize complex views heavily because they decouple exactly how application layers read the data from how internal DBA arrays index the tables underneath.","lg:col-span-2","primary","primary")}
{theory_card("Abstraction and Structural Security","Security is the principal real-world catalyst for establishing explicit Views. Subsuming arbitrary `WHERE` structures entirely into the view string forces the user out of interacting directly with raw payloads. For instance, creating a View named `PEDIATRIC_WARD_VIEW` that masks its exact `WHERE dept_id = 4` prevents an end-user from maliciously dropping or overwriting standard patient blocks located inside other isolated wards entirely since the user cannot access raw internal fields.","","secondary","secondary")}
{theory_card("Execution Logistics: Simple Vs Complex Views","A 'Simple' view refers explicitly to data originating exclusively from one isolated Base Table containing no generic math operations, constraints, distinct markers, or limits. Because Simple views maintain strict unified 1-to-1 mappings mapped backward directly onto their base table, they remain wholly 'Updatable', allowing DML `INSERT` logic seamlessly mirroring operations. Complex Views aggressively integrate deep mappings involving multiple generic tables via explicitly `JOIN` structured overlays and mathematically evaluated fields via aggregation groups; execution renders these outputs irrevocably fully Read-Only architectures.","lg:col-span-2","primary","primary")}
{theory_card("The Mandatory 'WITH CHECK OPTION' Boundary","When interacting with updatable structural Views, executing raw inserts technically runs the risk of inserting specific configurations completely outside the target range filters of the primary view conditions. `WITH CHECK OPTION` explicitly locks all associated mutations aggressively into validating their resultant array values against the specific base table `WHERE` clause binding the explicit View construct, otherwise generating exact fatal violation errors on submission instantly protecting context arrays.","","secondary","secondary")}
</div>"""

    proc = ol_steps([
        "Authenticate and set environment schema leveraging `USE hospital_db;`.",
        "Generate an atomic Simple View extracting distinct isolated structural columns restricting sensitive metadata.",
        "Produce an array-locking Updatable View constrained entirely via the strict `WITH CHECK OPTION` logic bounds.",
        "Analyze output boundaries by maliciously deploying an out-of-scope `INSERT` command explicitly targeting the Updatable View boundaries.",
        "Draft a heavy Complex View architecture leveraging embedded `JOIN` logic and grouping constructs spanning strictly across 3 distinct array structures.",
        "Target the deployed structures natively mimicking exact table selections securely restricting standard DML alterations preventing modification attempts.",
        "Identify internal meta arrays validating deployment success.",
        "Cleanse completely deploying final standard DDL layout `DROP VIEW` commands protecting long term integrity cycles."
    ])

    code = code_block(f"""{cmt("-- Practical 08: Instantiating Logical Views for Structural Segregation")}
{kw("USE")} {tbl("hospital_db")};

{cmt("-- ────────── 1. SIMPLE VIEW ESTABLISHMENT ──────────")}
{cmt("-- Shielding Patient emails and actual diagnosis structures from low-auth users.")}
{kw("CREATE OR REPLACE VIEW")} {tbl("V_Patient_Public_Mask")} {kw("AS")}
{kw("SELECT")} {tbl("patient_id")}, {tbl("name")}, {tbl("gender")}, {tbl("age")} 
{kw("FROM")} {tbl("PATIENT")};

{cmt("-- Validation: Retrieving the explicit layer masking underlying table properties.")}
{kw("SELECT")} * {kw("FROM")} {tbl("V_Patient_Public_Mask")} {kw("LIMIT")} {num("3")};

{cmt("-- ────────── 2. COMPLEX JOIN-VIEW ESTABLISHMENT ──────────")}
{cmt("-- Extracting fully combined metadata across 3 tables eliminating user join parsing burdens.")}
{kw("CREATE VIEW")} {tbl("V_Hospital_Financial_Overview")} {kw("AS")}
{kw("SELECT")} {tbl("p.name")} {kw("AS")} {tbl("Patient_Name")}, {tbl("b.total_amount")} {kw("AS")} {tbl("Billed_Invoice")}, {tbl("d.name")} {kw("AS")} {tbl("Attending_Physician")} 
{kw("FROM")} {tbl("BILL")} {tbl("b")}
{kw("JOIN")} {tbl("PATIENT")} {tbl("p")} {kw("ON")} {tbl("b.patient_id")} = {tbl("p.patient_id")}
{kw("JOIN")} {tbl("APPOINTMENT")} {tbl("a")} {kw("ON")} {tbl("a.patient_id")} = {tbl("p.patient_id")}
{kw("JOIN")} {tbl("DOCTOR")} {tbl("d")} {kw("ON")} {tbl("a.doctor_id")} = {tbl("d.doctor_id")};

{cmt("-- Executing identical SELECT logic masking massively extensive relational structures.")}
{kw("SELECT")} * {kw("FROM")} {tbl("V_Hospital_Financial_Overview")} {kw("ORDER BY")} {tbl("Billed_Invoice")} {kw("DESC LIMIT")} {num("3")};

{cmt("-- Attempting an INSERT on Complex view will absolutely trigger Error Code 1471")}
{cmt("-- The target table V_Hospital_Financial_Overview of the INSERT is not insertable-into.")}

{cmt("-- ────────── 3. UPDATABLE VIEWS WITH BOUNDARY CHECKS ──────────")}
{cmt("-- Instantiating isolated scopes parsing exclusively explicitly targeting Cardiology block tables.")}
{kw("CREATE VIEW")} {tbl("V_Cardiology_Isolation")} {kw("AS")}
{kw("SELECT")} * {kw("FROM")} {tbl("DOCTOR")} {kw("WHERE")} {tbl("dept_id")} = {num("1")}
{kw("WITH CHECK OPTION")};

{cmt("-- Legitimate Insert logic mirroring parameters accepted perfectly by underlying structural tables.")}
{kw("INSERT INTO")} {tbl("V_Cardiology_Isolation")} ({tbl("name")}, {tbl("specialization")}, {tbl("dept_id")}) 
{kw("VALUES")} ({str_("'Dr. Test Cardio'")}, {str_("'Cardiologist'")}, {num("1")});

{cmt("-- Attempting explicitly malformed boundary logic injection into Cardiology view directly.")}
{cmt("-- Error Code 1369. CHECK OPTION failed 'hospital_db.V_Cardiology_Isolation'")}
{cmt("/* ")}
{cmt("   INSERT INTO V_Cardiology_Isolation (name, dept_id) VALUES ('Dr. Oncology Hacker', 5);")}
{cmt("*/")}

{cmt("-- ────────── 4. AGGREGATED STATISTICAL READ-ONLY VIEW ──────────")}
{kw("CREATE VIEW")} {tbl("V_Department_Payroll_Stats")} {kw("AS")}
{kw("SELECT")} {tbl("dept_id")}, {fn("SUM")}({tbl("salary")}) {kw("AS")} {tbl("Total_Payroll")}, {fn("COUNT")}(*) {kw("AS")} {tbl("Staff_Size")}
{kw("FROM")} {tbl("DOCTOR")} 
{kw("GROUP BY")} {tbl("dept_id")};

{cmt("-- View deployed metrics calculation completely abstracting complex logic parsing.")}
{kw("SELECT")} * {kw("FROM")} {tbl("V_Department_Payroll_Stats")};

{cmt("-- ────────── 5. CLEANUP DEPLOYMENT COMMANDS ──────────")}
{kw("DROP VIEW IF EXISTS")} {tbl("V_Patient_Public_Mask")};
{kw("DROP VIEW IF EXISTS")} {tbl("V_Hospital_Financial_Overview")};
{kw("DROP VIEW IF EXISTS")} {tbl("V_Cardiology_Isolation")};
{kw("DROP VIEW IF EXISTS")} {tbl("V_Department_Payroll_Stats")};
""")
    output = out_table(
        ["Patient_Name","Billed_Invoice","Attending_Physician"],
        [["Kunal Das","95000.00","Dr. Sanjay Gupta"],
         ["Rajeev Nair","45000.00","Dr. Arjun Sharma"],
         ["Ravi Kumar","15000.00","Dr. Vikram Joshi"]],
        "Result: Extract output isolating logical readouts exclusively across massive 3 table JOIN view."
    )

    conclusion = """<p class="text-on-surface font-body leading-relaxed mb-4">
By utilizing standard definition syntax to declare explicitly structured Views, we isolated deeply complex execution sequences entirely behind singular functional blocks. This demonstrated absolute efficiency maintaining standard security firewalls restricting unauthorized parameter tampering specifically leveraging internal structural evaluations utilizing precise `WITH CHECK OPTION` modifiers ensuring relational stability completely. Understanding explicitly what factors force computational evaluations converting simplistic inputs against totally Read-Only restrictions limits unintentional destruction sequences completely globally during intensive integrations.
</p>"""
    return build_page(8,"Views","Group B","Virtual Tables",
        "Creating and manipulating virtual mapping matrices securing execution abstractions.",
        aim, theory, proc, code, output, conclusion, "")


if __name__ == "__main__":
    from generate_base import write_practical
    write_practical(6, p06(), BASE_DIR)
    write_practical(7, p07(), BASE_DIR)
    write_practical(8, p08(), BASE_DIR)
    print("Phase 2 (Practicals 6-8) fully updated and expanded!")
