const PRACTICALS = [
      {
        num: 1, title: "Study of MySQL", group: "A", icon: "terminal",
        desc: "Explore the architecture, storage engines, ACID properties, and fundamental characteristics of MySQL.",
        theory: `<h3>What is MySQL?</h3><p>MySQL is an open-source RDBMS developed in 1995, now maintained by Oracle. It organises data into related tables with rows and columns, and powers over 50% of the world's web applications — WordPress, Facebook, Twitter, YouTube.</p><h3 style="margin-top:16px;">Three-Tier Architecture</h3><div style="display:grid;grid-template-columns:1fr;gap:8px;margin:12px 0;"><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;border-left:3px solid var(--primary);"><strong style="color:var(--primary);">1. Client Layer</strong> — mysql CLI, Workbench, JDBC/ODBC connectors</div><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;border-left:3px solid var(--secondary);"><strong style="color:var(--secondary);">2. SQL Layer</strong> — Parser, Query Optimizer, Query Cache, Execution Engine</div><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;border-left:3px solid var(--green);"><strong style="color:var(--green);">3. Storage Engine Layer</strong> — InnoDB (default, ACID), MyISAM (fast reads), MEMORY (RAM-based), ARCHIVE</div></div><h3 style="margin-top:16px;">ACID Properties</h3><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px;"><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;text-align:center;"><div style="color:var(--primary);font-family:var(--font-headline);font-weight:700;font-size:20px;">A</div><div style="font-family:var(--font-label);font-size:10px;text-transform:uppercase;letter-spacing:0.1em;">Atomicity</div></div><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;text-align:center;"><div style="color:var(--primary);font-family:var(--font-headline);font-weight:700;font-size:20px;">C</div><div style="font-family:var(--font-label);font-size:10px;text-transform:uppercase;letter-spacing:0.1em;">Consistency</div></div><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;text-align:center;"><div style="color:var(--primary);font-family:var(--font-headline);font-weight:700;font-size:20px;">I</div><div style="font-family:var(--font-label);font-size:10px;text-transform:uppercase;letter-spacing:0.1em;">Isolation</div></div><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;text-align:center;"><div style="color:var(--primary);font-family:var(--font-headline);font-weight:700;font-size:20px;">D</div><div style="font-family:var(--font-label);font-size:10px;text-transform:uppercase;letter-spacing:0.1em;">Durability</div></div></div><div style="margin-top:16px;padding:14px;background:rgba(255,185,85,0.05);border:1px solid rgba(255,185,85,0.1);border-radius:10px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#67e8f9;">SELECT</span> VERSION();   <span style="color:#6b7280;">-- MySQL version</span>
<span style="color:#67e8f9;">SELECT</span> USER();      <span style="color:#6b7280;">-- logged-in user</span>
<span style="color:#67e8f9;">SHOW</span> DATABASES;    <span style="color:#6b7280;">-- list all databases</span>
<span style="color:#67e8f9;">SHOW</span> ENGINES;      <span style="color:#6b7280;">-- available storage engines</span>
<span style="color:#67e8f9;">CREATE</span> DATABASE dbms_lab;
<span style="color:#67e8f9;">USE</span> dbms_lab;</code></pre></div>`,
        tasks: ["Understand the 3-tier MySQL architecture: Client → SQL Layer → Storage Engine", "Study all four ACID properties with banking/healthcare examples", "Learn storage engines: InnoDB (ACID), MyISAM (read-heavy), MEMORY (volatile)", "Connect to MySQL: mysql -u root -p and run SELECT VERSION(); SELECT USER();", "Run SHOW DATABASES; and study the 4 system databases", "Run SHOW ENGINES; to see all available storage engines", "Inspect configuration: SHOW VARIABLES LIKE 'max_connections';", "Create a practice database: CREATE DATABASE dbms_lab; USE dbms_lab;", "Run SHOW STATUS LIKE 'Uptime'; to see server statistics", "Document all observations in your lab journal with explanations"],
        viva: [{ q: "What is the difference between MySQL and SQL?", a: "SQL is a language used to query and manage databases. MySQL is a Relational DBMS that uses SQL as its query language." }, { q: "Name and explain the default storage engine in MySQL.", a: "InnoDB is the default since MySQL 5.5. It supports ACID transactions, row-level locking, foreign keys, and crash recovery via redo/undo logs." }, { q: "What are the four ACID properties?", a: "Atomicity (transaction is all-or-nothing), Consistency (DB moves between valid states), Isolation (concurrent transactions don't interfere), Durability (committed data survives crashes)." }, { q: "What port does MySQL listen on?", a: "MySQL listens on TCP port 3306 by default." }, { q: "What is the difference between InnoDB and MyISAM?", a: "InnoDB supports transactions, foreign keys, row-level locking, and crash recovery. MyISAM uses table-level locking, is faster for read-heavy workloads, but has no transaction support." }]
      },
      {
        num: 2, title: "MySQL Installation & Configuration", group: "A", icon: "database",
        desc: "Install MySQL Community Edition, configure security settings, and manage user privileges.",
        theory: `<h3>MySQL Editions</h3><p>MySQL Community Edition (free, open-source) is sufficient for all academic and most production needs. Enterprise Edition adds advanced monitoring, backup, and firewall. MySQL listens on TCP port 3306.</p><h3 style="margin-top:16px;">Configuration File (my.cnf)</h3><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;margin:12px 0;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#6b7280;"># Key configuration parameters</span>
max_connections        = 151
innodb_buffer_pool_size = 2G   <span style="color:#6b7280;"># 70-80% of RAM</span>
character-set-server   = utf8mb4
collation-server       = utf8mb4_unicode_ci</code></pre></div><h3 style="margin-top:16px;">User Management</h3><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#67e8f9;">CREATE USER</span> 'labuser'@'localhost' <span style="color:#67e8f9;">IDENTIFIED BY</span> 'Lab@1234';
<span style="color:#67e8f9;">GRANT ALL PRIVILEGES ON</span> dbms_lab.* <span style="color:#67e8f9;">TO</span> 'labuser'@'localhost';
<span style="color:#67e8f9;">FLUSH PRIVILEGES</span>;
<span style="color:#67e8f9;">SHOW GRANTS FOR</span> 'labuser'@'localhost';</code></pre></div>`,
        tasks: ["Download MySQL Community Edition from dev.mysql.com/downloads", "Install with Developer Default setup type (Server + Workbench + Shell)", "Set a strong root password during installation", "Run mysql_secure_installation to remove anonymous users and test database", "Connect as root: mysql -u root -p and verify with SELECT VERSION();", "Create a dedicated lab user with restricted privileges", "Grant SELECT, INSERT, UPDATE on dbms_lab.* to the lab user", "Test the new user by connecting and running SHOW DATABASES;", "Create a read-only user with only SELECT privileges", "Inspect configuration: SHOW VARIABLES LIKE 'character_set_server';"],
        viva: [{ q: "What does mysql_secure_installation do?", a: "It sets the root password, removes anonymous users, disables remote root login, drops the test database, and reloads privilege tables." }, { q: "What is the principle of least privilege?", a: "Users should only be granted the minimum permissions needed for their tasks — never global ALL PRIVILEGES unless absolutely necessary." }, { q: "What is UTF8MB4 and why use it instead of UTF8?", a: "UTF8MB4 supports the full Unicode character set including 4-byte characters (emoji, rare CJK characters). Old UTF8 in MySQL only supports 3-byte characters and misses emojis." }, { q: "What does FLUSH PRIVILEGES do?", a: "It reloads the grant tables from the mysql database, applying any permission changes immediately without restarting the server." }]
      },
      {
        num: 3, title: "SQLite Architecture & Study", group: "A", icon: "schema",
        desc: "Study SQLite as a serverless, zero-configuration, file-based database engine with Python integration.",
        theory: `<h3>What is SQLite?</h3><p>SQLite is a self-contained, serverless, zero-configuration, transactional SQL database engine. It reads and writes directly to a single disk file (.db). Every Android and iOS device has SQLite built in — it is the most deployed database engine in the world with over 1 trillion active deployments.</p><h3 style="margin-top:16px;">SQLite vs MySQL</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0;"><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;border-left:3px solid var(--primary);"><strong style="color:var(--primary);">SQLite</strong><p style="font-size:14px;margin-top:8px;">Serverless, file-based, zero setup, 600KB footprint, built into Python/Android/iOS</p></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;border-left:3px solid var(--secondary);"><strong style="color:var(--secondary);">MySQL</strong><p style="font-size:14px;margin-top:8px;">Client-server, network access, user management, high concurrency, enterprise features</p></div></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;margin-top:8px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#6b7280;">-- SQLite dot-commands (CLI control, not SQL)</span>
.open college.db      <span style="color:#6b7280;">-- open/create database</span>
.headers on           <span style="color:#6b7280;">-- show column names</span>
.mode column          <span style="color:#6b7280;">-- formatted output</span>
.tables               <span style="color:#6b7280;">-- list all tables</span>
.schema Students      <span style="color:#6b7280;">-- show CREATE statement</span>
PRAGMA table_info(Students); <span style="color:#6b7280;">-- column metadata</span></code></pre></div>`,
        tasks: ["Install SQLite3 (pre-installed on Mac; sudo apt install sqlite3 on Ubuntu)", "Open a database: sqlite3 college.db and enable .headers on  .mode column", "Create Students table with INTEGER PRIMARY KEY AUTOINCREMENT, TEXT, REAL, CHECK constraints", "Insert 15 student records using a multi-row INSERT VALUES statement", "Run SELECT * FROM Students; to verify all 15 rows were inserted", "Filter with WHERE Branch = 'IT' and sort with ORDER BY CGPA DESC", "Use GROUP BY Branch with COUNT(*) and AVG(CGPA) aggregation", "Run .schema Students to view the CREATE TABLE DDL", "Export results to a file with .output report.txt then SELECT, then .output stdout", "Run PRAGMA table_info(Students); to inspect column metadata", "Drop the table: DROP TABLE IF EXISTS Students; and exit: .quit"],
        viva: [{ q: "When would you choose SQLite over MySQL?", a: "SQLite is ideal for embedded devices, mobile apps, desktop software, local browser storage, prototyping, and single-user applications. MySQL is better for multi-user, networked, high-write applications." }, { q: "What is type affinity in SQLite?", a: "SQLite uses storage class affinity rather than strict typing. A column declared INT stores INTEGER. Declared VARCHAR stores TEXT. The system is flexible and won't reject mismatched types." }, { q: "What is AUTOINCREMENT in SQLite?", a: "AUTOINCREMENT ensures the ROWID is always increasing and never reused, even after deletions. Without it, SQLite may reuse IDs from deleted rows." }, { q: "How do PRAGMA commands differ from SQL?", a: "PRAGMA commands control SQLite behaviour and query metadata — they are not standard SQL. Examples: PRAGMA table_info(), PRAGMA foreign_keys = ON, PRAGMA integrity_check." }]
      },
      {
        num: 4, title: "ER Diagram Design", group: "B", icon: "table_chart",
        desc: "Design a Hospital Management System ER diagram and implement it in MySQL with all relationship types.",
        theory: `<h3>ER Diagram Fundamentals</h3><p>An Entity-Relationship Diagram (Peter Chen, 1976) is a visual blueprint of a database. It models Entities (rectangles), Attributes (ovals), and Relationships (diamonds).</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0;"><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><strong style="color:var(--primary);">Cardinality Types</strong><p style="font-size:13px;margin-top:8px;">1:1 — Person ↔ Passport<br>1:N — Department → Employees<br>M:N — Student ↔ Courses</p></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><strong style="color:var(--secondary);">Attribute Types</strong><p style="font-size:13px;margin-top:8px;">Simple: Name, Age<br>Composite: Address → Street, City<br>Derived: Age from DOB (dashed oval)<br>Multivalued: Phone numbers (double oval)</p></div></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;margin-top:8px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#67e8f9;">CREATE TABLE</span> Treatment (
  TreatmentID <span style="color:var(--tertiary);">INT</span> PRIMARY KEY AUTO_INCREMENT,
  PatientID   <span style="color:var(--tertiary);">INT</span> NOT NULL,  <span style="color:#6b7280;">-- FK to Patient</span>
  DoctorID    <span style="color:var(--tertiary);">INT</span> NOT NULL,  <span style="color:#6b7280;">-- FK to Doctor</span>
  Diagnosis   <span style="color:var(--tertiary);">VARCHAR</span>(200),
  Cost        <span style="color:var(--tertiary);">DECIMAL</span>(8,2),
  <span style="color:#67e8f9;">FOREIGN KEY</span> (PatientID) <span style="color:#67e8f9;">REFERENCES</span> Patient(PatientID),
  <span style="color:#67e8f9;">FOREIGN KEY</span> (DoctorID)  <span style="color:#67e8f9;">REFERENCES</span> Doctor(DoctorID)
);</code></pre></div>`,
        tasks: ["Identify entities: Doctor, Ward, Patient, Treatment for Hospital Management System", "List all attributes for each entity, marking PKs, composite, derived, multivalued", "Determine cardinality: Patient-Ward (1:N), Patient-Doctor (M:N via Treatment)", "Determine participation constraints (total vs partial) for each relationship", "Draw the complete ER diagram with all attribute types and relationship notations", "Convert ER diagram to relational schema: M:N → junction table with two FKs", "Implement in MySQL: CREATE DATABASE hospital_db; create all 4 tables with constraints", "Insert 5 doctors, 5 wards, 10 patients using multi-row INSERT statements", "Insert 10 treatment records linking patients to doctors", "Run a 3-table JOIN to verify all relationships work correctly"],
        viva: [{ q: "What is the difference between Strong and Weak entities?", a: "Strong entities have an independent primary key. Weak entities depend on an owner entity for identification and use a composite key (owner PK + partial key)." }, { q: "How do you resolve an M:N relationship in SQL?", a: "Create a junction/associative table with foreign keys referencing both entities' primary keys. For Patient-Doctor, the Treatment table is the junction." }, { q: "What are participation constraints?", a: "Total participation (double line) means every entity must participate in the relationship. Partial participation (single line) means participation is optional." }, { q: "What is an EER diagram?", a: "Extended ER diagrams add Specialization (top-down decomposition), Generalization (bottom-up combining), and Aggregation (treating a relationship as an entity) to standard ER notation." }]
      },
      {
        num: 5, title: "DDL + Normalization", group: "B", icon: "query_stats",
        desc: "Apply DDL commands and normalize a schema from unnormalized form through 1NF, 2NF, and 3NF.",
        theory: `<h3>Normal Forms</h3><div style="margin-bottom:16px;"><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;margin-bottom:8px;border-left:3px solid var(--primary);"><strong style="color:var(--primary);">1NF</strong> — Atomic values only, no repeating groups, unique rows</div><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;margin-bottom:8px;border-left:3px solid var(--primary);"><strong style="color:var(--primary);">2NF</strong> — 1NF + no partial dependencies (every non-key attribute depends on the FULL composite key)</div><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;margin-bottom:8px;border-left:3px solid var(--tertiary);"><strong style="color:var(--tertiary);">3NF</strong> — 2NF + no transitive dependencies (non-key attributes don't depend on other non-key attributes)</div><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;"><strong style="color:var(--primary);">BCNF</strong> — Every determinant must be a candidate key</div></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#6b7280;">-- ALTER TABLE examples</span>
<span style="color:#67e8f9;">ALTER TABLE</span> Students <span style="color:#67e8f9;">ADD COLUMN</span> Email <span style="color:var(--tertiary);">VARCHAR</span>(100);
<span style="color:#67e8f9;">ALTER TABLE</span> Students <span style="color:#67e8f9;">MODIFY COLUMN</span> Email <span style="color:var(--tertiary);">VARCHAR</span>(150);
<span style="color:#67e8f9;">ALTER TABLE</span> Students <span style="color:#67e8f9;">RENAME COLUMN</span> Email <span style="color:#67e8f9;">TO</span> StudentEmail;
<span style="color:#67e8f9;">ALTER TABLE</span> Students <span style="color:#67e8f9;">DROP COLUMN</span> StudentEmail;
<span style="color:#67e8f9;">RENAME TABLE</span> Students <span style="color:#67e8f9;">TO</span> Enrolled;</code></pre></div>`,
        tasks: ["Draw an UNF table with multi-valued Courses column — explain update, insert, delete anomalies", "Apply 1NF: ensure atomic values, create composite primary key (StudentID, CourseID)", "Identify all functional dependencies in the 1NF table", "Apply 2NF: remove partial dependencies — separate Students and Courses tables", "Apply 3NF: remove transitive dependencies — separate Professors table", "Create the 3NF schema in MySQL: CREATE DATABASE college_db; create 4 tables", "Insert 15 students into NF2_Students table using multi-row INSERT", "Insert 3 professors and 5 courses into 3NF tables", "Demonstrate ALTER TABLE: ADD COLUMN, MODIFY COLUMN, RENAME COLUMN, DROP COLUMN", "Use RENAME TABLE and verify final structure with DESCRIBE and SHOW CREATE TABLE"],
        viva: [{ q: "What is a transitive dependency?", a: "When a non-key attribute X depends on another non-key attribute Y (X → Y → Z where Y is not a key). Removing this moves Y and Z to a separate table." }, { q: "What is a partial dependency?", a: "When a non-key attribute depends on only PART of a composite primary key, not the full key. This violates 2NF." }, { q: "What anomalies does normalization prevent?", a: "Update anomaly (same data in multiple rows), Insert anomaly (cannot insert without providing unrelated data), Delete anomaly (deleting one record accidentally removes unrelated needed data)." }, { q: "Difference between DDL and DML?", a: "DDL (CREATE, ALTER, DROP, TRUNCATE, RENAME) defines and modifies database structure. DML (SELECT, INSERT, UPDATE, DELETE) manipulates data within that structure." }]
      },
      {
        num: 6, title: "Constraints, ALTER & DROP", group: "B", icon: "storage",
        desc: "Implement all six SQL constraint types, modify schemas with ALTER TABLE, and understand DELETE vs TRUNCATE vs DROP.",
        theory: `<h3>All Constraint Types</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:16px;"><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;"><span style="color:var(--primary);font-family:var(--font-mono);font-weight:700;">PRIMARY KEY</span></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;"><span style="color:var(--primary);font-family:var(--font-mono);font-weight:700;">FOREIGN KEY</span></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;"><span style="color:var(--secondary);font-family:var(--font-mono);font-weight:700;">UNIQUE</span></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;"><span style="color:var(--secondary);font-family:var(--font-mono);font-weight:700;">NOT NULL</span></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;"><span style="color:var(--tertiary);font-family:var(--font-mono);font-weight:700;">CHECK</span></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;"><span style="color:var(--tertiary);font-family:var(--font-mono);font-weight:700;">DEFAULT</span></div></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#67e8f9;">CREATE TABLE</span> Employee (
  EmpID   <span style="color:var(--tertiary);">INT</span> PRIMARY KEY AUTO_INCREMENT,
  EmpName <span style="color:var(--tertiary);">VARCHAR</span>(100) NOT NULL,
  Salary  <span style="color:var(--tertiary);">DECIMAL</span>(10,2) CHECK (Salary >= 15000),
  Email   <span style="color:var(--tertiary);">VARCHAR</span>(100) UNIQUE,
  DeptID  <span style="color:var(--tertiary);">INT</span> NOT NULL,
  <span style="color:#67e8f9;">FOREIGN KEY</span> (DeptID) <span style="color:#67e8f9;">REFERENCES</span> Department(DeptID)
    <span style="color:#67e8f9;">ON DELETE CASCADE ON UPDATE CASCADE</span>
);</code></pre></div>`,
        tasks: ["Create Department table with PRIMARY KEY, NOT NULL, UNIQUE, CHECK, DEFAULT constraints", "Create Employee table with FOREIGN KEY referencing Department with ON DELETE CASCADE", "Insert 5 departments and 15 employees using multi-row INSERT statements", "Test CHECK constraint violation: insert Salary < 15000 — observe ERROR 3819", "Test NOT NULL violation: insert without EmpName — observe ERROR 1364", "Test UNIQUE violation: duplicate Email — observe ERROR 1062", "Test FOREIGN KEY violation: invalid DeptID — observe ERROR 1452", "Demonstrate ON DELETE CASCADE: delete a department and verify child employees are auto-deleted", "Practice ALTER TABLE: ADD COLUMN, MODIFY COLUMN, RENAME COLUMN, ADD CONSTRAINT, DROP COLUMN", "Compare DELETE (targeted, rollback-able) vs TRUNCATE (all rows, resets AUTO_INCREMENT) vs DROP (destroys table)"],
        viva: [{ q: "What is the difference between DELETE, TRUNCATE, and DROP?", a: "DELETE removes specific rows via WHERE, can be rolled back, fires triggers, doesn't reset AUTO_INCREMENT. TRUNCATE removes ALL rows instantly, cannot be rolled back, resets AUTO_INCREMENT. DROP destroys the entire table structure and all data permanently." }, { q: "What does ON DELETE CASCADE do?", a: "When a parent row is deleted, all child rows referencing it via FOREIGN KEY are automatically deleted too." }, { q: "Can a UNIQUE column contain NULL?", a: "Yes. In MySQL, a UNIQUE column can contain multiple NULL values because NULL is not equal to NULL (NULL != NULL in SQL)." }, { q: "What is the difference between PRIMARY KEY and UNIQUE?", a: "A table can have only one PRIMARY KEY and it cannot contain NULL. A table can have multiple UNIQUE constraints and UNIQUE columns can contain NULL." }]
      },
      {
        num: 7, title: "SQL Queries & Operators", group: "B", icon: "security",
        desc: "Master DML with WHERE operators, aggregate functions, GROUP BY, HAVING, subqueries, and set operations.",
        theory: `<h3>SELECT Execution Order</h3><div style="background:var(--bg-darkest);padding:12px;border-radius:8px;margin-bottom:16px;font-family:var(--font-mono);font-size:13px;">FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT</div><h3>Key SQL Features</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:16px;"><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><strong style="color:var(--secondary);">WHERE Operators</strong><p style="font-size:13px;margin-top:8px;">BETWEEN, IN, NOT IN, LIKE (%), IS NULL, AND, OR, NOT</p></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><strong style="color:var(--secondary);">Aggregate Functions</strong><p style="font-size:13px;margin-top:8px;">COUNT(*), SUM, AVG, MAX, MIN with GROUP BY / HAVING</p></div></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#6b7280;">-- Subquery: above average salary</span>
<span style="color:#67e8f9;">SELECT</span> EmpName, Salary <span style="color:#67e8f9;">FROM</span> Employee
<span style="color:#67e8f9;">WHERE</span> Salary > (<span style="color:#67e8f9;">SELECT</span> <span style="color:#67e8f9;">AVG</span>(Salary) <span style="color:#67e8f9;">FROM</span> Employee);

<span style="color:#6b7280;">-- UNION (removes duplicates)</span>
<span style="color:#67e8f9;">SELECT</span> EmpName <span style="color:#67e8f9;">FROM</span> Employee <span style="color:#67e8f9;">WHERE</span> Salary > 65000
<span style="color:#67e8f9;">UNION</span>
<span style="color:#67e8f9;">SELECT</span> EmpName <span style="color:#67e8f9;">FROM</span> Employee <span style="color:#67e8f9;">WHERE</span> DeptID = 1;</code></pre></div>`,
        tasks: ["Practice SELECT with DISTINCT, ORDER BY ASC/DESC, LIMIT on Employee table", "Filter with WHERE using BETWEEN, IN, NOT IN, LIKE patterns (%, _), IS NULL, IS NOT NULL", "Combine conditions with AND, OR — test operator precedence with parentheses", "Run aggregate functions: COUNT(*), SUM(Salary), AVG(Salary), MAX(Salary), MIN(Salary)", "Apply GROUP BY DeptID and HAVING AVG(Salary) > 50000 to filter grouped results", "Use WITH ROLLUP to add department subtotals and a grand total row", "Write a non-correlated subquery: employees earning above company average", "Write a correlated subquery: top earner in each department", "Use a derived table (subquery in FROM): departments with average salary > 50000", "Practice UNION (deduplicates) and UNION ALL (keeps duplicates) between two SELECT queries", "Simulate INTERSECT and MINUS using IN and NOT IN", "Run UPDATE with WHERE and DELETE with WHERE on the Employee table"],
        viva: [{ q: "Difference between WHERE and HAVING?", a: "WHERE filters individual rows BEFORE grouping. HAVING filters groups AFTER GROUP BY — it can only reference aggregated values or GROUP BY columns." }, { q: "What does % mean in LIKE?", a: "% matches zero or more characters. 'A%' matches any string starting with A. '%ar%' matches any string containing 'ar'. '_' matches exactly one character." }, { q: "How does AVG handle NULLs?", a: "AVG, SUM, COUNT(col) all ignore NULL values. Only COUNT(*) includes rows with NULLs." }, { q: "What is the difference between correlated and non-correlated subqueries?", a: "Non-correlated: executes once, independent of outer query. Correlated: references outer query's row and executes once per outer row — slower but more powerful." }, { q: "What does UNION ALL do differently from UNION?", a: "UNION removes duplicate rows (requires sorting). UNION ALL keeps ALL rows including duplicates and is faster because no deduplication step is needed." }]
      },
      {
        num: 8, title: "Views in SQL", group: "B", icon: "code_blocks",
        desc: "Create simple, complex, and security views; use WITH CHECK OPTION; inspect view metadata.",
        theory: `<h3>What are Views?</h3><p>A View is a virtual table defined by a stored SELECT query. It stores no data — every query against a view executes the underlying SELECT dynamically. Views simplify complex queries, enhance security by hiding sensitive columns, and provide data abstraction.</p><h3 style="margin-top:16px;">Simple vs Complex Views</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0;"><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;border-left:3px solid var(--green);"><strong style="color:var(--green);">Simple View</strong><p style="font-size:13px;margin-top:8px;">Single table, no aggregates — UPDATABLE (INSERT/UPDATE/DELETE work through it)</p></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;border-left:3px solid var(--error);"><strong style="color:var(--error);">Complex View</strong><p style="font-size:13px;margin-top:8px;">JOINs, GROUP BY, aggregates, DISTINCT — NOT UPDATABLE</p></div></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#67e8f9;">CREATE OR REPLACE VIEW</span> IT_Employees <span style="color:#67e8f9;">AS</span>
<span style="color:#67e8f9;">SELECT</span> EmpID, EmpName, Salary <span style="color:#67e8f9;">FROM</span> Employee
<span style="color:#67e8f9;">WHERE</span> DeptID = 1 <span style="color:#67e8f9;">WITH CHECK OPTION</span>;

<span style="color:#6b7280;">-- List all views</span>
<span style="color:#67e8f9;">SHOW FULL TABLES WHERE</span> Table_type = 'VIEW';
<span style="color:#67e8f9;">SHOW CREATE VIEW</span> IT_Employees;</code></pre></div>`,
        tasks: ["Create a simple view IT_Employees showing only DeptID = 1 employees", "Query IT_Employees with SELECT * and verify only IT employees appear", "Create a complex JOIN view: Employee_Full_Details joining Employee and Department tables", "Query the JOIN view with a WHERE Salary > 50000 filter", "Create an aggregate view: Department_Summary with COUNT, AVG, SUM, MAX, MIN salary", "Create a security view: Employee_Public_Info hiding the Salary column", "Create an updatable view with WITH CHECK OPTION and test a valid salary update", "Try an update that violates CHECK OPTION (reduces salary below threshold) — observe ERROR 1369", "Use CREATE OR REPLACE VIEW to update IT_Employees to add the Gender column", "Inspect view metadata with INFORMATION_SCHEMA.VIEWS and SHOW CREATE VIEW", "Use SHOW FULL TABLES WHERE Table_type = 'VIEW' to list all views", "DROP VIEW IF EXISTS Employee_Public_Info"],
        viva: [{ q: "Can you INSERT through a View?", a: "Only through simple updatable views (single table, no aggregates, no DISTINCT, no GROUP BY, no subqueries). Complex views with JOINs or aggregates are NOT updatable — MySQL returns Error 1471." }, { q: "What does WITH CHECK OPTION do?", a: "It ensures that any INSERT or UPDATE through the view still satisfies the view's WHERE clause. Prevents data modifications that would make the row invisible through the view." }, { q: "Does MySQL support Materialized Views?", a: "No. MySQL does not natively support Materialized Views. The workaround is to create a regular table, populate it with INSERT...SELECT, and refresh it via an EVENT or TRIGGER." }, { q: "What is the advantage of using views for security?", a: "You can grant SELECT on a view but NOT on the underlying table. Users can query the view but cannot access sensitive columns (salary, SSN) even if they know the table exists." }]
      },
      {
        num: 9, title: "Implementation of Joins", group: "B", icon: "settings_ethernet",
        desc: "Master INNER, LEFT, RIGHT, FULL OUTER, SELF, and CROSS JOINs with performance analysis using EXPLAIN.",
        theory: `<h3>Why JOINs?</h3><p>JOINs re-assemble normalized data split across tables. Always index JOIN columns for O(log n) vs O(n²) Cartesian scans.</p><h3 style="margin-top:16px;">All JOIN Types</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0;"><div style="background:rgba(168,232,255,0.04);border:1px solid rgba(168,232,255,0.1);padding:12px;border-radius:8px;"><strong style="color:var(--primary);">INNER JOIN</strong><p style="font-size:13px;">Matched rows only from both tables</p></div><div style="background:rgba(74,222,128,0.04);border:1px solid rgba(74,222,128,0.1);padding:12px;border-radius:8px;"><strong style="color:var(--green);">LEFT JOIN</strong><p style="font-size:13px;">ALL left rows + matching right (NULL if no match)</p></div><div style="background:rgba(255,185,85,0.04);border:1px solid rgba(255,185,85,0.1);padding:12px;border-radius:8px;"><strong style="color:var(--secondary);">RIGHT JOIN</strong><p style="font-size:13px;">ALL right rows + matching left (NULL if no match)</p></div><div style="background:rgba(192,132,252,0.04);border:1px solid rgba(192,132,252,0.1);padding:12px;border-radius:8px;"><strong style="color:var(--purple);">SELF JOIN</strong><p style="font-size:13px;">Table joined with itself (hierarchies, org charts)</p></div></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#6b7280;">-- SELF JOIN: employee-manager hierarchy</span>
<span style="color:#67e8f9;">SELECT</span> E.EmpName AS Employee, M.EmpName AS Manager
<span style="color:#67e8f9;">FROM</span> Employee E
<span style="color:#67e8f9;">LEFT JOIN</span> Employee M <span style="color:#67e8f9;">ON</span> E.ManagerID = M.EmpID;</code></pre></div>`,
        tasks: ["Add ManagerID column to Employee table for SELF JOIN: ALTER TABLE Employee ADD COLUMN ManagerID INT;", "Create Project table with DeptID FK and insert 5 projects", "Run INNER JOIN Employee + Department — verify only employees with valid DeptID appear", "Run LEFT JOIN Department + Employee — verify ALL departments appear including empty ones", "Run RIGHT JOIN Department + Employee — verify ALL employees appear", "Simulate FULL OUTER JOIN using UNION of LEFT and RIGHT JOIN queries", "Run SELF JOIN: Employee E LEFT JOIN Employee M ON E.ManagerID = M.EmpID to show employee-manager pairs", "Run CROSS JOIN on a small subset — observe the M×N Cartesian product row count", "Write a 3-table JOIN: Employee + Department + Project in a single query", "Run EXPLAIN on a JOIN query to verify indexes are being used"],
        viva: [{ q: "What is a SELF JOIN?", a: "A table joined with itself using two different aliases. Used for hierarchical data like employee-manager relationships or comparing rows within the same table." }, { q: "Difference between CROSS JOIN and INNER JOIN?", a: "CROSS JOIN produces a Cartesian product (M × N rows) with no condition. INNER JOIN filters based on an ON condition and typically returns far fewer rows." }, { q: "How do you simulate FULL OUTER JOIN in MySQL?", a: "MySQL doesn't support FULL OUTER JOIN directly. Simulate it with: SELECT ... LEFT JOIN ... UNION SELECT ... RIGHT JOIN ..." }, { q: "What does EXPLAIN tell you about a JOIN?", a: "EXPLAIN shows which index was used (key column), how many rows were examined (rows column), and the join type (type: ref/range=good, ALL=full scan=bad)." }]
      },
      {
        num: 10, title: "Stored Procedures & Functions", group: "C", icon: "lan",
        desc: "Build stored procedures with IN/OUT/INOUT parameters, control flow, loops, and user-defined functions.",
        theory: `<h3>Stored Procedures vs Functions</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0;"><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;border-left:3px solid var(--primary);"><strong style="color:var(--primary);">Procedure</strong><p style="font-size:13px;margin-top:8px;">Called with CALL. Can have IN/OUT/INOUT params. Cannot be used in SELECT. Can use transactions.</p></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;border-left:3px solid var(--secondary);"><strong style="color:var(--secondary);">Function</strong><p style="font-size:13px;margin-top:8px;">RETURNS a single value. Used directly in SELECT/WHERE. Must be DETERMINISTIC. Cannot use transactions.</p></div></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#67e8f9;">DELIMITER</span> $$
<span style="color:#67e8f9;">CREATE PROCEDURE</span> GetEmpGrade(IN p_EmpID INT)
<span style="color:#67e8f9;">BEGIN</span>
  DECLARE v_Salary DECIMAL(10,2);
  <span style="color:#67e8f9;">SELECT</span> Salary <span style="color:#67e8f9;">INTO</span> v_Salary <span style="color:#67e8f9;">FROM</span> Employee <span style="color:#67e8f9;">WHERE</span> EmpID=p_EmpID;
  <span style="color:#67e8f9;">IF</span> v_Salary >= 70000 <span style="color:#67e8f9;">THEN</span> <span style="color:#67e8f9;">SELECT</span> 'Executive';
  <span style="color:#67e8f9;">ELSEIF</span> v_Salary >= 55000 <span style="color:#67e8f9;">THEN</span> <span style="color:#67e8f9;">SELECT</span> 'Senior';
  <span style="color:#67e8f9;">ELSE</span> <span style="color:#67e8f9;">SELECT</span> 'Junior';
  <span style="color:#67e8f9;">END IF</span>;
<span style="color:#67e8f9;">END</span>$$
<span style="color:#67e8f9;">DELIMITER</span> ;
<span style="color:#67e8f9;">CALL</span> GetEmpGrade(5);</code></pre></div>`,
        tasks: ["Set DELIMITER to $$ before creating procedures", "Create Procedure 1 (IN): GetEmployeesByDept — accepts DeptID, returns sorted employees", "CALL GetEmployeesByDept(1) and verify correct department employees are returned", "Create Procedure 2 (OUT): GetDeptStats returning count, average, max salary via OUT parameters", "CALL GetDeptStats(1, @cnt, @avg, @mx) then SELECT @cnt, @avg, @mx", "Create Procedure 3 (INOUT): ApplyBonus — modifies salary by percentage in-place", "Create Procedure 4 with IF-ELSEIF-ELSE: GetEmpGrade categorizing employees", "Create Procedure 5 with WHILE loop: SalaryProjection showing 5-year salary growth in a TEMPORARY TABLE", "Reset DELIMITER to semicolon: DELIMITER ;", "Create Function CalcTax(salary) with tax brackets — use directly in SELECT", "Create Function ExperienceLevel(joinDate) — use in SELECT to show experience category", "Create a procedure with EXIT HANDLER FOR SQLEXCEPTION demonstrating safe error handling"],
        viva: [{ q: "Difference between a Procedure and a Function in MySQL?", a: "Functions return a single value using RETURN and can be used in SELECT/WHERE. Procedures use CALL, can have multiple OUT parameters, and can execute transactions. Functions cannot modify data (in standard SQL mode)." }, { q: "What is DELIMITER used for in MySQL?", a: "DELIMITER changes the statement terminator so MySQL doesn't interpret semicolons inside the procedure body as end-of-statement. Common choice: DELIMITER $$ then reset with DELIMITER ;" }, { q: "What is the difference between IN, OUT, and INOUT parameters?", a: "IN: value passed into procedure, read-only inside. OUT: procedure writes a value to be read by caller. INOUT: both passes a value in AND returns a modified value out." }, { q: "What is a DETERMINISTIC function?", a: "A function that always returns the same result for the same input parameters. Required declaration when binary logging is enabled. Non-deterministic functions may produce different results (e.g., using NOW() or RAND())." }]
      },
      {
        num: 11, title: "Database Triggers", group: "C", icon: "cloud_done",
        desc: "Implement all six trigger types for automatic validation, business rules, and complete audit logging.",
        theory: `<h3>All Six Trigger Types</h3><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin:12px 0;"><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;font-size:12px;"><span style="color:var(--primary);">BEFORE INSERT</span></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;font-size:12px;"><span style="color:var(--green);">AFTER INSERT</span></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;font-size:12px;"><span style="color:var(--primary);">BEFORE UPDATE</span></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;font-size:12px;"><span style="color:var(--green);">AFTER UPDATE</span></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;font-size:12px;"><span style="color:var(--primary);">BEFORE DELETE</span></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;font-size:12px;"><span style="color:var(--green);">AFTER DELETE</span></div></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#67e8f9;">CREATE TRIGGER</span> trg_before_insert_emp
<span style="color:#67e8f9;">BEFORE INSERT ON</span> Employee <span style="color:#67e8f9;">FOR EACH ROW</span>
<span style="color:#67e8f9;">BEGIN</span>
  <span style="color:#67e8f9;">IF</span> NEW.Salary < 15000 <span style="color:#67e8f9;">THEN</span>
    <span style="color:#67e8f9;">SIGNAL SQLSTATE</span> '45000'
      <span style="color:#67e8f9;">SET MESSAGE_TEXT</span> = 'Salary must be >= 15000';
  <span style="color:#67e8f9;">END IF</span>;
<span style="color:#67e8f9;">END</span>$$</code></pre></div>`,
        tasks: ["Create Employee_Audit table with columns for EmpID, Action, OldName, NewName, OldSalary, NewSalary, ChangedBy, ChangedAt", "Set DELIMITER to $$", "Create BEFORE INSERT trigger: validate Salary >= 15000 using SIGNAL; auto-format EmpName to Title Case", "Create AFTER INSERT trigger: log new employee details to Employee_Audit", "Create BEFORE UPDATE trigger: prevent salary reduction with SIGNAL; auto-update JoinDate on dept transfer", "Create AFTER UPDATE trigger: log all field changes (old vs new values) to Employee_Audit", "Create BEFORE DELETE trigger: protect employees with Salary > 90000 using SIGNAL", "Create AFTER DELETE trigger: log deleted employee details", "Reset DELIMITER to semicolon", "Test: INSERT 'rAHUL sharma' with Salary 35000 — verify auto-formatted to 'Rahul Sharma' and audit log entry", "Test: UPDATE Rahul's Salary to 60000 — verify audit log captures both old and new salary", "Test: DELETE Rahul — verify audit log entry. Then try deleting a high earner — observe SIGNAL rejection"],
        viva: [{ q: "What are the NEW and OLD pseudo-records in triggers?", a: "NEW contains the new row values for INSERT and UPDATE. OLD contains the previous row values for UPDATE and DELETE. In BEFORE triggers you can MODIFY NEW values; in AFTER triggers you can only READ them." }, { q: "How do you raise a custom error from a trigger?", a: "Use SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Your error message'; SQLSTATE 45000 is the generic unhandled user-defined exception code." }, { q: "Does TRUNCATE fire row-level triggers?", a: "No. TRUNCATE removes all rows without firing row-level INSERT/UPDATE/DELETE triggers because it is a DDL operation, not a row-by-row DML." }, { q: "What is the most common real-world use of AFTER INSERT/UPDATE/DELETE triggers?", a: "Audit logging — recording who changed what data and when. Required for SOX compliance (financial), HIPAA (healthcare), and GDPR (personal data) regulations." }]
      },
      {
        num: 12, title: "Cursors in MySQL", group: "C", icon: "account_tree",
        desc: "Implement explicit cursors for row-by-row processing with NOT FOUND handlers and TEMPORARY TABLEs.",
        theory: `<h3>Cursor Lifecycle</h3><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0;"><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;"><div style="color:var(--primary);font-family:var(--font-mono);font-weight:700;">DECLARE</div><div style="font-size:11px;margin-top:4px;">Define with SELECT</div></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;"><div style="color:var(--secondary);font-family:var(--font-mono);font-weight:700;">OPEN</div><div style="font-size:11px;margin-top:4px;">Execute SELECT</div></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;"><div style="color:var(--green);font-family:var(--font-mono);font-weight:700;">FETCH</div><div style="font-size:11px;margin-top:4px;">Read one row</div></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;text-align:center;"><div style="color:var(--error);font-family:var(--font-mono);font-weight:700;">CLOSE</div><div style="font-size:11px;margin-top:4px;">Release memory</div></div></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code>DECLARE emp_cursor CURSOR FOR
  SELECT EmpID, EmpName, Salary FROM Employee;
<span style="color:#6b7280;">-- NOT FOUND handler MUST come AFTER cursor</span>
DECLARE CONTINUE HANDLER FOR NOT FOUND
  SET v_Done = TRUE;

OPEN emp_cursor;
process_loop: LOOP
  FETCH emp_cursor INTO v_ID, v_Name, v_Sal;
  IF v_Done THEN LEAVE process_loop; END IF;
  <span style="color:#6b7280;">-- per-row business logic here</span>
END LOOP;
CLOSE emp_cursor;</code></pre></div>`,
        tasks: ["Set DELIMITER to $$", "Declare variables for all cursor columns: EmpID, Name, Salary, DeptID, Category, Done flag", "Declare emp_cursor with SELECT EmpID, EmpName, Salary, DeptID FROM Employee ORDER BY DeptID", "Declare CONTINUE HANDLER FOR NOT FOUND to set v_Done = TRUE (must come AFTER cursor declaration)", "Create TEMPORARY TABLE EmpReport to accumulate categorized results", "OPEN the cursor, run the LOOP, FETCH each row into declared variables", "Apply IF-ELSEIF logic: Executive (≥70000) / Senior (≥55000) / Mid-Level (≥40000) / Junior", "Check v_Done inside the loop — IF v_Done THEN LEAVE process_loop; END IF", "INSERT categorized row into EmpReport inside the loop", "CLOSE the cursor after the loop exits", "SELECT * FROM EmpReport and SELECT Category, COUNT(*) GROUP BY Category to show results", "Create a second procedure DeptRunningTotal with a cursor that resets running total when department changes"],
        viva: [{ q: "Difference between implicit and explicit cursors?", a: "Implicit cursors are automatically created by MySQL for single-row SELECT...INTO statements. Explicit cursors are declared by the programmer with DECLARE CURSOR FOR to process multi-row result sets row by row." }, { q: "Why must the NOT FOUND handler be declared AFTER the cursor?", a: "MySQL requires the declaration order: variables → cursors → handlers. The NOT FOUND handler must reference the cursor's v_Done flag, so it must come after the cursor declaration." }, { q: "When should you use a cursor instead of set-based SQL?", a: "Cursors should be a last resort. Use them ONLY when per-row logic genuinely cannot be expressed as a single set operation. Prefer UPDATE with CASE or window functions. Cursors are 10-100x slower than equivalent set-based SQL on large tables." }, { q: "What happens if you forget CLOSE on a cursor?", a: "The cursor and its associated result set remain in memory for the duration of the procedure. On procedures called frequently, this wastes server memory. Always CLOSE every cursor you OPEN." }]
      },
      {
        num: 13, title: "Project Proposal & SRS", group: "D", icon: "reorder",
        desc: "Write a comprehensive IEEE 830 SRS for Library Management System and implement its database.",
        theory: `<h3>SRS Document Structure (IEEE 830-1998)</h3><div style="margin-bottom:16px;"><div style="display:flex;gap:10px;align-items:flex-start;margin-bottom:12px;"><span style="color:var(--primary);font-family:var(--font-mono);">01.</span><div><strong>Introduction</strong><p style="font-size:14px;color:var(--text-dim);">Purpose, scope, definitions, references, overview of the document.</p></div></div><div style="display:flex;gap:10px;align-items:flex-start;margin-bottom:12px;"><span style="color:var(--primary);font-family:var(--font-mono);">02.</span><div><strong>Overall Description</strong><p style="font-size:14px;color:var(--text-dim);">Product perspective, user roles (Student, Faculty, Librarian, Admin), constraints.</p></div></div><div style="display:flex;gap:10px;align-items:flex-start;margin-bottom:12px;"><span style="color:var(--primary);font-family:var(--font-mono);">03.</span><div><strong>Specific Requirements</strong><p style="font-size:14px;color:var(--text-dim);">FR01-FR10 (Login, Search, Issue, Return, Fine, Reports...) + Non-functional (performance, security, availability).</p></div></div><div style="display:flex;gap:10px;align-items:flex-start;"><span style="color:var(--primary);font-family:var(--font-mono);">04.</span><div><strong>Appendices</strong><p style="font-size:14px;color:var(--text-dim);">ER Diagram, DFD Level 0 & 1, Use Case Diagram, Data Dictionary.</p></div></div></div><div style="background:var(--bg-darkest);padding:10px;border-radius:8px;font-family:var(--font-mono);font-size:12px;">Non-Functional: Response &lt; 2s | 99.9% availability | bcrypt passwords | HTTPS</div>`,
        tasks: ["Define project title: Library Management System. Write problem statement, objectives, scope", "Document FR01-FR10: Login, Book Search, Issue, Return, Fine Calculation, Member Management, Inventory, Reports, Notifications, Audit Log", "Document Non-Functional Requirements: sub-2s response, 99.9% uptime, bcrypt + HTTPS security, mobile-first UI", "Define user roles: Student (search/borrow/return), Faculty (higher book limit), Librarian (issue/return), Admin (full access)", "Create Level 0 DFD: system as one process, Student and Librarian as external entities", "Create Level 1 DFD: decompose into Authentication, Book Management, Borrowing Management sub-processes", "Design ER diagram: Member, Book, Librarian, Borrowing entities with attributes and relationships", "Implement in MySQL: CREATE DATABASE library_db; create all 4 tables with constraints", "Insert 15 member records (Student/Faculty/Staff types) using multi-row INSERT", "Insert 10 book records with ISBN, Title, Author, TotalCopies, AvailableCopies, ShelfLocation", "Implement FR-04 (Issue Book): INSERT into Borrowing + UPDATE AvailableCopies - 1", "Implement FR-09 (Overdue Fine): query with DATEDIFF × Rs. 5/day calculation"],
        viva: [{ q: "What is IEEE 830?", a: "IEEE 830-1998 is the standard for Software Requirements Specifications. It defines a structured format for documenting system requirements that is complete, consistent, verifiable, and unambiguous." }, { q: "Difference between functional and non-functional requirements?", a: "Functional requirements describe WHAT the system does (login, search, issue book). Non-functional requirements describe HOW WELL it does it (performance, security, availability, scalability)." }, { q: "What is a DFD and its levels?", a: "Data Flow Diagram models data movement through a system. Level 0 (Context Diagram) shows the entire system as one process. Level 1 decomposes it into sub-processes. Level 2 further decomposes each sub-process." }, { q: "How do ER diagram entities map to database tables?", a: "Each strong entity becomes a table. M:N relationships become junction tables. Multivalued attributes become separate tables. Composite attributes are flattened into individual columns. Derived attributes are not stored." }]
      },
      {
        num: 14, title: "ER Diagram & Database Design (Project)", group: "D", icon: "history",
        desc: "Final project: implement indexes, transactions with savepoints, and query optimization using EXPLAIN.",
        theory: `<h3>Final Database Design</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0;"><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><div style="color:var(--primary);font-size:11px;font-family:var(--font-mono);text-transform:uppercase;margin-bottom:6px;">Indexes</div><p style="font-size:13px;">B-Tree indexes for O(log n) lookups. Composite indexes follow leftmost prefix rule. EXPLAIN verifies usage.</p></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><div style="color:var(--secondary);font-size:11px;font-family:var(--font-mono);text-transform:uppercase;margin-bottom:6px;">Transactions</div><p style="font-size:13px;">START TRANSACTION → SAVEPOINT → ROLLBACK TO / COMMIT for atomic multi-step operations.</p></div></div><div style="background:var(--bg-darkest);padding:14px;border-radius:10px;"><pre style="font-family:var(--font-mono);font-size:13px;overflow-x:auto;white-space:pre-wrap;"><code><span style="color:#67e8f9;">CREATE INDEX</span> idx_emp_dept_salary
  <span style="color:#67e8f9;">ON</span> Employee(DeptID, Salary); <span style="color:#6b7280;">-- composite</span>

<span style="color:#67e8f9;">EXPLAIN</span> <span style="color:#67e8f9;">SELECT</span> * <span style="color:#67e8f9;">FROM</span> Employee
<span style="color:#67e8f9;">WHERE</span> DeptID = 1 <span style="color:#67e8f9;">AND</span> Salary > 50000;
<span style="color:#6b7280;">-- type: ref (index used) ← good</span>
<span style="color:#6b7280;">-- type: ALL (full scan) ← bad</span>

<span style="color:#67e8f9;">START TRANSACTION</span>;
  <span style="color:#67e8f9;">UPDATE</span> Employee <span style="color:#67e8f9;">SET</span> Salary = Salary - 3000 <span style="color:#67e8f9;">WHERE</span> EmpID = 1;
  <span style="color:#67e8f9;">SAVEPOINT</span> after_debit;
  <span style="color:#67e8f9;">UPDATE</span> Employee <span style="color:#67e8f9;">SET</span> Salary = Salary + 3000 <span style="color:#67e8f9;">WHERE</span> EmpID = 2;
<span style="color:#67e8f9;">COMMIT</span>;</code></pre></div>`,
        tasks: ["Run SHOW INDEX FROM Employee; to see existing indexes", "Create single-column index: CREATE INDEX idx_emp_salary ON Employee(Salary);", "Create composite index: CREATE INDEX idx_emp_dept_salary ON Employee(DeptID, Salary);", "Run EXPLAIN SELECT * FROM Employee WHERE DeptID = 1 AND Salary > 50000; — verify type is ref/range not ALL", "Compare EXPLAIN output before and after index creation", "Run EXPLAIN on a JOIN query — verify the DeptID FK index is used", "Query INFORMATION_SCHEMA.STATISTICS to list all indexes in college_db", "Drop a redundant index: DROP INDEX idx_emp_salary ON Employee;", "Transaction 1 (COMMIT): atomic salary bonus transfer between two employees", "Transaction 2 (SAVEPOINT): insert 3 employees, ROLLBACK TO savepoint 2 (undo only employee 3), COMMIT", "Transaction 3 (ROLLBACK): DELETE dept 4 employees, verify deletion, full ROLLBACK, verify restoration", "Run the final departmental report with GROUP BY and ORDER BY — verify with EXPLAIN"],
        viva: [{ q: "What is the leftmost prefix rule for composite indexes?", a: "A composite index on (DeptID, Salary) can be used for queries filtering on DeptID alone or DeptID+Salary, but NOT for queries filtering only on Salary. The leftmost column must be in the WHERE clause." }, { q: "What does EXPLAIN's 'type' field tell you?", a: "The access method: const/eq_ref (best, single row lookup), ref/range (index scan, good), ALL (full table scan, worst — add an index). The key field shows which index was chosen." }, { q: "What is the difference between ROLLBACK and ROLLBACK TO SAVEPOINT?", a: "ROLLBACK undoes ALL changes since START TRANSACTION. ROLLBACK TO SAVEPOINT name undoes only changes AFTER that savepoint, preserving earlier changes within the same transaction." }, { q: "What are the four isolation levels in MySQL?", a: "READ UNCOMMITTED (allows dirty reads), READ COMMITTED (no dirty reads), REPEATABLE READ (default — no non-repeatable reads), SERIALIZABLE (complete isolation, lowest concurrency)." }]
      }
    ];